In [1]:
import pandas as pd

In [5]:
df1 = pd.read_csv("Data/data_imdb_Action.csv", sep = ";")
df2 = pd.read_csv("Data/data_imdb_Adventure.csv", sep = ";")
df3 = pd.read_csv("Data/data_imdb_Animation.csv", sep = ";")
df4 = pd.read_csv("Data/data_imdb_Biography.csv", sep = ";")
df5 = pd.read_csv("Data/data_imdb_Comedy.csv", sep = ";")
df6 = pd.read_csv("Data/data_imdb_Crime.csv", sep = ";")
df7 = pd.read_csv("Data/data_imdb_Drama.csv", sep = ";")
df8 = pd.read_csv("Data/data_imdb_Family.csv", sep = ";")
df9 = pd.read_csv("Data/data_imdb_Fantasy.csv", sep = ";")
df10 = pd.read_csv("Data/data_imdb_Film-Noir.csv", sep = ";")
df11 = pd.read_csv("Data/data_imdb_History.csv", sep = ";")
df12 = pd.read_csv("Data/data_imdb_Horror.csv", sep = ";")
df13 = pd.read_csv("Data/data_imdb_Music.csv", sep = ";")
df14 = pd.read_csv("Data/data_imdb_Musical.csv", sep = ";")
df15 = pd.read_csv("Data/data_imdb_Mystery.csv", sep = ";")
df16 = pd.read_csv("Data/data_imdb_Romance.csv", sep = ";")
df17 = pd.read_csv("Data/data_imdb_Sci-Fi.csv", sep = ";")
df18 = pd.read_csv("Data/data_imdb_Sport.csv", sep = ";")
df19 = pd.read_csv("Data/data_imdb_Thriller.csv", sep = ";")
df20 = pd.read_csv("Data/data_imdb_War.csv", sep = ";")
df21 = pd.read_csv("Data/data_imdb_Western.csv", sep = ";")

In [9]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21],  ignore_index=True)
df = df.drop(columns= ["Unnamed: 0"])
df

,name,year,certificate,runtime,genre,rating,metascore,text-muted,director,stars
0,The Dark Knight : Le Chevalier noir,2008,Tous publics,152,"['Action', ' Crime', ' Drama ']",9.0,84,When the menace known as the Joker wreaks havo...,"['Christopher Nolan', None]","['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
1,Le Seigneur des anneaux : Le Retour du roi,2003,Tous publics,201,"['Action', ' Adventure', ' Drama ']",9.0,94,Gandalf and Aragorn lead the World of Men agai...,"['Peter Jackson', None]","['Elijah Wood', 'Viggo Mortensen', 'Ian McKell..."
2,Kill Bill: The Whole Bloody Affair,2011,NaN,247,"['Action', ' Crime', ' Thriller ']",8.8,-1,The Bride must kill her ex-boss and lover Bill...,"['Quentin Tarantino', None]","['Uma Thurman', 'Lucy Liu', 'Vivica A. Fox', '..."
3,Inception,2010,Tous publics,148,"['Action', ' Adventure', ' Sci-Fi ']",8.8,74,A thief who steals corporate secrets through t...,"['Christopher Nolan', None]","['Leonardo DiCaprio', 'Joseph Gordon-Levitt', ..."
4,Le Seigneur des anneaux : Les Deux Tours,2002,Tous publics,179,"['Action', ' Adventure', ' Drama ']",8.8,87,While Frodo and Sam edge closer to Mordor with...,"['Peter Jackson', None]","['Elijah Wood', 'Ian McKellen', 'Viggo Mortens..."
...,...,...,...,...,...,...,...,...,...,...
23932,Apportez-moi la tête d'Alfredo Garcia,1974,12,112,"['Action', ' Crime', ' Drama ']",7.4,80,An American barroom pianist and his prostitute...,"['Sam Peckinpah', None]","['Warren Oates', 'Isela Vega', 'Robert Webber'..."
23933,L'homme des hautes plaines,1973,Tous publics,105,"['Drama', ' Mystery', ' Western ']",7.4,69,A gun-fighting stranger comes to the small set...,"['Clint Eastwood', None]","['Clint Eastwood', 'Verna Bloom', 'Marianna Hi..."
23934,Les cow-boys,1972,Tous publics,134,"['Adventure', ' Drama', ' Western ']",7.4,52,Rancher Wil Andersen is forced to hire inexper...,"['Mark Rydell', None]","['John Wayne', 'Roscoe Lee Browne', 'Bruce Der..."
23935,100 dollars pour un shérif,1969,12,128,"['Adventure', ' Drama', ' Western ']",7.4,83,"A drunken, hard-nosed U.S. Marshal and a Texas...","['Henry Hathaway', None]","['John Wayne', 'Kim Darby', 'Glen Campbell', '..."
23936,Hombre,1967,Tous publics,111,['Western '],7.4,80,"John Russell, disdained by his ""respectable"" f...","['Martin Ritt', None]","['Paul Newman', 'Fredric March', 'Richard Boon..."

In [10]:
df.to_csv("all_films.csv", sep=';')